Добавляет файл functions.js
htmlacademy-javascript/2173899-kekstagram-30 pull request #2
Opened 2023-10-07 11:57 UTC by SSNIPG

2023-10-09 15:00 UTC, baileys-li requested changes

2023-10-09 15:00 UTC, baileys-li commented on js/functions.js
> +function checksStringLength(string, number) {
Лучше называть обезличенными глаголами 
```suggestion
function checkStringLength(string, number) {
```

2023-10-09 15:00 UTC, baileys-li commented on js/functions.js
> +function palindromeChecker(string) {
Лучше называть глаголами
```suggestion
function isPalindrome(string) {
```

2023-10-09 15:00 UTC, baileys-li commented on js/functions.js
> +function returnNumber(string) {
Доп кейсы пока не проходит
![image](https://github.com/htmlacademy-javascript/2173899-kekstagram-30/assets/47776594/91dd7f22-28b6-
415e-bfab-2432e917d253)

2023-10-09 15:00 UTC, baileys-li commented
А ещё напоминаю про стрелки из доп критериев

2023-10-10 19:11 UTC, SSNIPG commented on js/functions.js
> +function returnNumber(string) {
Я правильно понимаю что если я передаю в функцию число то она должна вернуть тоже число, если дробное число то должно вернутся дробное число, если отрицательное число то вернётся отрицательное число?

2023-10-11 14:22 UTC, baileys-li commented on js/functions.js
> +function returnNumber(string) {
@SSNIPG не, не совсем. Глянь примеры из дз, ну или сегодня рассмотрим

2023-10-11 18:56 UTC, merged